### ISSUE TITLE
Application performs handoff to FDA to download original files within same window, making it difficulty to navigate back to original SDR record

### ISSUE THREAD

**Issue by nmwolf** [NYULibraries/spatial_data_repository#312] opened 2024-03-10 13:39 UTC
This is behaving as expected, but could be a candidate for platform improvement. Currently, when a user click to download orginal files, it hands it off to the FDA bitstream link, keeping user in same browser tab. After download, the page remains on the blank bitstream download page.

The user likely still needs to see the SDR record page, and therefore will have to use back button to head back to SDR record. This is not ideal, however, because it will sometimes re-trigger the download and fail to move back to the SDR record.

A better approach might be to have a handoff back to the SDR record, or else initiate the process in a new tab (if that does not violate accessibility issues).

**Comment by gulshan11** [comment] 2024-07-24 19:34
Reassigning to @spilth as its suspected to be SDR issue.

**Comment by spilth** [comment] 2024-07-24 20:28
Here are the steps to reproduce this issue:

1. Load https://archive.nyu.edu/
1. Click on Username in upper right and choose Logout
1. Load https://geo.nyu.edu/
1. Click on Logout
1. Load https://geo.nyu.edu/catalog/nyu-2451-37402
1. Click on Login to View and Download
1. Click Download
1. Choose Original GeoTIFF
1. Taken to https://archive.nyu.edu/retrieve/78744/nyu_2451_37402.zip
1. Click NYU users: Login
1. Fill in NetID & Password
1. File is downloaded
1. User is left on blank page

**Comment by spilth** [comment] 2024-07-25 16:13
@nmwolf I see potential solutions to this:

1. When we link to restricted downloads, we force the link to open in a new tab. This way the blank page is separate from the flow on geo.nyu.edu.
2. We figure out how to pass along a `return_url` or equivalent to the login flow on archive.nyu.edu so we can redirect users back to the geo.nyu.edu page with the download link (which should work now that you're logged in) as opposed to the archive.nyu.edu page which leaves you on a blank page.
    - This assumes both archive.nyu.edu and the Shibboleth systems support some kind of return URL parameter. It's still a little awkward since the user would have to click the download link again now that they're logged in.

**Comment by spilth** [comment] 2024-08-07 17:10
This fix has been deployed to Production.

**Closed by spilth** 2024-08-07 17:10 UTC
Labels: look and feel enhancements
