### ISSUE TITLE
Line, Point, and some Polygon overlays disappear as user zooms in

### ISSUE THREAD

**Issue by nmwolf** [NYULibraries/spatial_data_repository#309] opened 2024-03-10 13:25 UTC
As a user zooms in on the Leaflet window, features will disappear after moving from zoom level 1 to 2 (e.g. one + click zoom in), especially for line and point features. Polygons sometimes will persist at closer zoom levels, but they too will disappear once you move past a certain zoom level.

Note that this behavior is weirdly inconsistent, and some vector records will perform as expected, others will not.

POINT EXAMPLE

Record: https://geo.nyu.edu/catalog/nyu-2451-34416

On original load, we see the points (note also lo-res rendering on a Mac retina screen):

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/b64a0685-2039-416f-8c2e-5ff4b7e8c786)

After one + click to Zoom in, the points dissappear:

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/0e5d910f-a267-4f45-8736-a6e105acdca5)

LINES EXAMPLE

Record: https://geo.nyu.edu/catalog/nyu-2451-33891

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/64379a7e-0343-4aa9-9b27-695e4541194e)

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/33683fa1-1226-48f5-9b50-3aa1a8cb8b01)

POLYGONS EXAMPLE

Record: https://geo.nyu.edu/catalog/nyu-2451-34425

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/ec78a96f-2b0b-4972-a246-b25fc2dbb38e)

![Image](https://github.com/NYULibraries/spatial_data_repository/assets/11075283/eed9c4bf-fb0f-48a9-9853-87e547ed5e54)

**Comment by spilth** [comment] 2024-07-16 15:28
I don't know if this is intended, but the data on this page won't load at all unless I'm connected to the VPN.

**Comment by spilth** [comment] 2024-07-16 17:01
Looking at this with @gulshan11. It looks like requests go to the restricted GeoServer but at certain zoom levels GeoServer just returns empty images, so I'm wondering if that's a configuration issue on the GeoServer side.

**Comment by spilth** [comment] 2024-07-16 17:36
I'm not sure if this means anything but I loaded both the WMS and WFS versions of this data source into QGIS and only the WFS returns visible data regardless of the zoom level.

![Image](https://github.com/user-attachments/assets/d429ba43-4c7c-43fb-ab18-361c8be37456)

**Comment by gulshan11** [comment] 2024-07-20 15:22
The download link isn't redirected to the specified shp file [EPSG:4326 Shapefile](https://geo.nyu.edu/catalog/nyu-2451-34416)

**Comment by gulshan11** [comment] 2024-08-15 19:24
The issue is resolved by upgrading to latest geoserver over the prod environment.

**Closed by gulshan11** 2024-08-15 19:24 UTC
Labels: bug
